apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}-staging
  name: {name}-staging
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}-staging
    spec:
      restartPolicy: Always
      containers:
      - name: {name}-staging
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        ports:
          - containerPort: 80
