export const legends = {
  'mammals:richness': { min: 1, max: 221 },
  'turtles:richness': { min: 1, max: 22 },
  'birds:richness': { min: 1, max: 1010 },
  'amphibians:richness': { min: 1, max: 179 },
  'cacti:richness': { min: 1, max: 93 },
  'conifers:richness': { min: 1, max: 49 },
  'all-taxa:richness': { min: 1, max: 1416 },
  'mammals:rarity': { min: 0, max: 1 },
  'birds:rarity': { min: 0, max: 1 },
  'turtles:rarity': { min: 0, max: 1 },
  'amphibians:rarity': { min: 0, max: 1 },
  'cacti:rarity': { min: 0, max: 1 },
  'conifers:rarity': { min: 0, max: 1 },
  'all-taxa:rarity': { min: 0, max: 1 },
  'mammals:richness_1km': { min: 8, max: 49 },
  'birds:richness_1km': { min: 1, max: 380 },
  'amphibians:richness_1km': { min: 3, max: 25 },
  'restio:richness_1km': { min: 1.35, max: 166 },
  'protea:richness_1km': { min: 0.005, max: 68 },
  'mammals:rarity_1km': { min: 8, max: 49 },
  'birds:rarity_1km': { min: 1, max: 380 },
  'amphibians:rarity_1km': { min: 3, max: 25 },
  'restio:rarity_1km': { min: 1, max: 166 },
  'protea:rarity_1km': { min: 1, max: 69 },
  'key-biodiversity-areas': { type: 'simple', label: 'Key Biodiversity Areas', color: 'green' },
  'road-building': { type: 'simple', label: 'Roads', color: 'red' },
  'private-reserves': { type: 'simple', label: 'Private Reserves', color: 'orange' },
  'urban-development': { type: 'simple', label: 'Urban Development', color: 'brown' },
  'protected-areas': { type: 'simple', label: 'Protected Areas', color: 'violet' },
  'conservation-areas': { type: 'simple', label: 'Conservation Areas', color: 'violet' },
  'human-pressures': { type: 'gradient', label: 'Human Pressures', color: 'black', min: 0, max: 100 },
  'prioritization-of-places': { type: 'gradient', label: 'Priority Places', color: 'priority', min: 0, max: 100 },
  'community-based-reserves': { type: 'simple', label: 'Community Based Reserves', color: 'red' },
  'community-based-conservation-areas': { type: 'simple', label: 'Community Based Conservation Areas', color: 'cbca' }
};
